# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZBAcSgECaQLBCvhBI2mjir-tIb8Og1y
"""

print("hello")

import tensorflow as tf
import numpy as np

celcius = np.array([180000,190000,170000,160000,150000,140000,130000])
farenheit = np.array([152969.84999999998,162969.84999999998,142969.84999999998,132969.84999999998,122969.84999999999,112969.84999999999,102969.85])
for a,b in enumerate(celcius):
  print("{} inlet pressure = {} outlet pressure".format(b,farenheit[a]))

machine_learning_model = tf.keras.layers.Dense(units=1,input_shape=[1])
machine_learning_model1 = tf.keras.layers.Dense(units=1)
machine_learning_model2 = tf.keras.layers.Dense(units=1)
model = tf.keras.Sequential([machine_learning_model,machine_learning_model1,machine_learning_model2])
model.compile(loss="mean_squared_error",optimizer = tf.keras.optimizers.Adam(0.1))

train = model.fit(celcius,farenheit,epochs=1200000,verbose=False)
print("finished model")

print(model.predict([689475.729]))

machine_learning_model.get_weights()